import type { NextPage } from "next";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import classes from "src/styles/Home.module.css";

type State = {
  id: string;
  title: string;
  author: string;
};

const PostsId: NextPage = () => {
  const router = useRouter();
  const [post, setPost] = useState<State>();

  const getPost = useCallback(async () => {
    const res = await fetch(`http://localhost:8080/posts/${router.query.id}`);
    const json = await res.json();
    setPost(json);
  }, [router.query.id]);

  useEffect(() => {
    getPost();
  }, [getPost]);

  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <Link href="/">
          <a>戻る</a>
        </Link>
        <h1 className={classes.title}>{post?.author}</h1>

        <p className={classes.description}>{post?.title}</p>
      </main>

      <footer className={classes.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={classes.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default PostsId;
