import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import classes from "src/styles/Home.module.css";

const Home: NextPage = () => {
  const [posts, setPosts] = useState([]);

  const getPosts = useCallback(async () => {
    const res = await fetch("http://localhost:8080/posts");
    const json = await res.json();
    setPosts(json);
  }, []);

  useEffect(() => {
    getPosts();
  }, [getPosts]);

  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <h1 className={classes.title}>Next.js!</h1>

        <p className={classes.description}>
          Get started by editing{" "}
          <code className={classes.code}>pages/index.js</code>
        </p>

        <div className={classes.grid}>
          {posts.map(({ id, title, author }) => {
            return (
              <Link key={id} href={`/posts/${id}`} legacyBehavior>
                <a className={classes.card}>
                  <h2>{author}</h2>
                  <p>{title}</p>
                </a>
              </Link>
            );
          })}
        </div>
      </main>

      <footer className={classes.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={classes.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
